### ISSUE TITLE
Upgrade issue:  Old versions of JDBC libraries are not removed on upgrade

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#1059]
**Describe the bug**

When running a CMS upgrade, new versions of JDBC drivers are correctly copied into <InstallDirectory>/jetty/base/lib/jdbc.  The problem is that the older version of the JDBC driver jars are not being removed by the upgrade process.  For example, if you look at the below directory listing, there are two versions of the Microsoft SQL Server jdbc driver, and because they both use the same driver class name, there is no guarantee that Jetty will pick the newer driver version. 

``
 Directory of C:\Rhythmyx\jetty\base\lib\jdbc

09/06/2023  01:19 PM    <DIR>          .
09/06/2023  01:20 PM    <DIR>          ..
07/19/2023  10:47 AM         3,853,921 db2jcc4.jar
07/19/2023  10:47 AM             1,013 db2jcc_license_cu.jar
09/06/2023  01:19 PM         3,232,770 derby-10.14.2.0.jar
09/06/2023  01:19 PM           588,394 derbyclient-10.14.2.0.jar
09/06/2023  01:19 PM           272,626 derbynet-10.14.2.0.jar
09/06/2023  01:19 PM           317,816 jtds-1.3.1.jar
07/19/2023  10:47 AM           294,726 jtds.jar
07/19/2023  10:47 AM           960,558 mssql-jdbc-7.1.3.jre8-preview.jar
09/06/2023  01:19 PM         1,327,642 mssql-jdbc-9.2.1.jre8.jar
09/06/2023  01:19 PM         2,739,670 ojdbc6-12.1.0.1.jar
``

**To Reproduce**

1. Install a 7.3.2 version of Rhythmyx
2. Upgrade it to the latest with java -jar perc-distribution-tree.jar <Rhythmyx Install Dir>
3. Check the <InstallDir>\jetty\base\lib\jdbc folder
4. You will see duplicate drivers new and old for mssql.

**Expected behavior**
Only the current version of each JDBC driver should be in the jdbc lib folder. 

**Versions Affected**
* 8.0.3
* 8.1.2
* 8.1.3
  
**Additional context**
I looked at the installation code.  This can't be done as part of the current ant installation process as all of the jars are on the classpath that is passed to ant.  I think this needs to be done from the Java process that controls the installation.  We can't just blow away the folder because a customer may have added their own drivers there.

**Comment by natechadwick** [comment]
Related to #1035

**Comment by sonydeswal74** [comment]
@natechadwick Following are the old jars or I am missing some?
"mssql-jdbc-7.1.3.jre8-preview.jar",
"jtds.jar",
 "db2jcc_license_cu.jar",
 "db2jcc4.jar"
