### ISSUE TITLE
Navigation Tab - After rearranging the items sequence, if user move to other item/tab and come back, the sequence is lost.

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1097]
**Describe the bug**

Navigation Tab - After rearranging the items sequence, if user move to other item/tab and come back, the sequence is lost.

**To Reproduce**

1. Go to Navigation Tab
2. Re-arranging the items sequence using drag/drop.
3. Click on some other item.
4. Come back to the previous item, the sequence was arranged for. The sequence is lost

**Expected behavior**

Any change in items sequence using drag/drop should persist.

**Additional context**
PSSiteSectionRestService.java file is related to this issue. Need to debug it.

**Comment by sonydeswal74** [comment]
@ramdev1980 please take latest code and test this bug. It should be fixed with above fix.
