### ISSUE TITLE
systemProperties bean name conflicts with the spring systemProperties bean  - it needs renamed

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1119]
**Describe the bug**

systemProperties bean name conflicts with the spring systemProperties bean  - it needs renamed to psSystemProperties, in PSSystemProperties.java and sitemanage-beans.xml files.

**To Reproduce**

**Expected behavior**
The bean name should match the class name. 

**Additional context**
These files are related to this issue:
PSSystemProperties.java
sitemanage-beans.xml
example:
<property name="systemProps">
            <ref bean="psSystemProperties"/>
        </property>

**Comment by natechadwick** [comment]
Fixed by #1124
