### ISSUE TITLE
Importing third party JS and CSS incorrectly during import site functionality

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1191]
**Describe the bug**

If a page has references to CDN hosted javascript or css resources then those are imported to web resources incorrectly.
They should be left intact on import.

For example:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js" integrity="sha512-6Uv+497AWTmj/6V14BsQioPrm3kgwmK9HYIyWP+vClykX52b0zrDGP7lajZoIY1nNlX4oQuh7zsGjmF7D0VZYA==" crossorigin="anonymous"></script>`

gets converted to 

`<script src="/web_resources/themes/TestSite4/import/cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js" integrity="sha512-6Uv+497AWTmj/6V14BsQioPrm3kgwmK9HYIyWP+vClykX52b0zrDGP7lajZoIY1nNlX4oQuh7zsGjmF7D0VZYA==" crossorigin="anonymous"></script>`

**To Reproduce**

1. Go to create site.
2. Create  site from url.
3. Click next.

**Expected behavior**

External links to CSS and JS  should be left intact on import.

**Versions Affected**
* <=8.1.4

**Comment by natechadwick** [comment]
Re-opening as now no js files with relative path are being imported.

**Comment by sonydeswal74** [comment]
Hi Nate,

   You want me to fix it? I can as I know why it is happening.

**Comment by natechadwick** [comment]
Hi Santosh!

If you have time, and a fix, I definitely won't say no!

-n

**Comment by natechadwick** [comment]
Latest on this is that the CSS / JS Links are now "" when importing a Template from a URL.  They are correct when a site is imported.

**Comment by natechadwick** [comment]
@ramdev1980 does that last PR resolve this?

**Comment by ramdev1980** [comment]
@natechadwick   This has been fixed.
