### ISSUE TITLE
Form Widget posts to 1st configured production DTS server instead of default publishing server DTS

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#1201]
**Describe the bug**

**To Reproduce**

1. Configure two production type delivery servers in <InstallDir>/rxconfig/DeliveryServers\delivery-servers.xml
2. Restart the CMS service
3. Configure the Default Publishing server for a site to use the 2nd production delivery server.
4. Add a Form Widget and configure it on a Page on the site.
5. Publish the page and submit the form,
6. View Source on the published page, note that the 1st production DTS server is listed for the form not the 2nd one as expected. 

**Expected behavior**
The Form widget should point to the configured DTS for the Default Publishing server of the site that the form widget is on. 

**Versions Affected**
* <=8.1.3

**Comment by natechadwick** [comment]
After this change, the server seems to be set to NONE if there is only one publishing server and you are unable to edit publishing servers to change the value.

**Comment by natechadwick** [comment]
@rgarg24  Can you take a look.  This is failing post upgrade. Unable to edit the publishing server or change the DTS server after upgrade to 8.1.4 - the server just stays at NONE with no error.

**Comment by rgarg24** [comment]
This issue is fixed and tested. It is working fine.
