### ISSUE TITLE
Images are not uploading while importing the site.

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1205]
**Describe the bug**

While importing a site, the images are not being uploaded in Asset folder.

**To Reproduce**

1. Import a site (using Create Site).
2. Preview pages of the imported site.
3. Images are missing in html pages.

**Expected behavior**

All site images should be uploaded with site import.

**Comment by natechadwick** [comment]
@ramdev1980  Are no images imported at all?

**Comment by natechadwick** [comment]
Marking this as closed as the issue is resolved.
