### ISSUE TITLE
Remove weak cipher: TLS_DH_RSA_WITH_AES_128_GCM_SHA256 

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#1219]
**Describe the bug**
Remove cipher TLS_DH_RSA_WITH_AES_128_GCM_SHA256 it has been flagged as weak.  The cipher is not listed in the configuration files by default for new installs but may be present on upgrades and it is still present in some of the code as a default.

**Comment by rgarg24** [comment]
Nate, 
There are still some references pending.

**Comment by rgarg24** [comment]
Fixed the bug through #1244
