### ISSUE TITLE
Display HTML is blank under Widget Builder until it is clicked

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1228]
**Describe the bug**

Display HTML is blank under Widget Builder until it is clicked

**To Reproduce**

1. Go to Widget Builder
2. Select a Widget and click edit.
3. Click on Display Tab.
4. Display HTML is blank

**Expected behavior**

Display HTML should be populated with saved content.

  
**Screenshots**

![image](https://github.com/percussion/percussioncms/assets/131112747/ed9e72bc-c177-41d7-8cc0-0ebec6ea0260)

**Comment by natechadwick** [comment]
Work around is to click into the Display HTML field, then it renders.
