### ISSUE TITLE
Blog list fails to render with Invocation of method 'newInstance' error

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1261]
**Describe the bug**

Blog list fails to render with Invocation of method 'newInstance' error
![image](https://github.com/percussion/percussioncms/assets/131112747/ea3e8ff1-a7fd-40aa-b9b0-d1e6c369431a)

**To Reproduce**

1. Create a blog list page, with blog list widget
2. add blogs to it.
3. Try to open , blog list page, you can see the error

**Expected behavior**

Blog list should work fine.

**Additional context**

lines which contains newInstance in percBlogIndexPage.xml, if commented it works. It is related to java version.

**Comment by natechadwick** [comment]
This looks like a java security policy change in more recent JRE versions.  We should replace the reflection in that velocity code with a Java extension method in the PSPageUtils class.
