### ISSUE TITLE
Resources under rx_resources/images css js/es need to be localized to the Spanish locale

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#395]
**Describe the bug**
The resources under rx_resources images, css, and js need to be localized to the spanish locale.  They are currently in english.

**To Reproduce**
1. Go to <installRoot>/rx_resources/css/es/, <installRoot>/rx_resources/js/es, <installRoot>/rx_resources/images/es
2. For any resources that display text that would be rendered in the UI, note that the text is in English.  

**Expected behavior**
The resources under the es locale should be in Spanish.

**Comment by ramdev1980** [comment]
Fixed
