### ISSUE TITLE
VelocitySwitchingTool incorrectly regenerates deleted legacy AppServer path

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#420]
**Describe the bug**
After using the VelocitySwitchingTool, if the AppServer folder had been previously removed, the new velocity classes / jars are copied to a new AppServer folder tree in addition to the jetty locations.  The AppServer deployment should be skipped if the folder has already been removed. 

**To Reproduce**
1. Delete <installdir>/AppServer
2. Run rxconfig/velocity/switchVelocityVersion.bat|sh and switch versions
3. Notice that the <InstallDIr>/AppServer folder is recreated.

**Expected behavior**
If the AppServer folder doesn't exist, the velocity switching scripts shouldn't recreate it.

Relates to #419

**Comment by Yashdeep2001** [comment]
Appserver file does no longer seem to be present. It is not being recreated
![Screenshot 2022-08-26 112448](https://user-images.githubusercontent.com/103224298/186968313-31d19c59-bb68-4715-80b9-ca4690e08870.png)

**Comment by mariosm1** [comment]
Tested on 8.1 and 732_20211210 patch and the velocity switching tool is not recreating the AppServer folder.
