### ISSUE TITLE
By default, there are 3 responsive templates. We need to capitalize "plain".

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#433]
This was tested on Version 8.0.3 Build 105

When adding a new template on the Designer component.  I selected “Response” templates.  2 of the 3 templates have proper capitalization.  We should capitalize “plain”.  See screenshot below:

![image-20220222-130323](https://user-images.githubusercontent.com/50147765/156371753-73b47659-faac-4ff2-a0f5-12a03b080fe3.png)

**Comment by natechadwick** [comment]
should be resolved, i'd rather put that propercase function into a shared utility js that is accessible there.
