### ISSUE TITLE
Console Warning when launching CMS

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#434]
This was reproduced on Version 8.0.3 Build 105

When I launch CMS, I opened the console and see a Console Warning message.  The Text of the message is as follows:

Depricated Feature Used:

The website requested a subresource from a network that it could only access because of its users' privileged network position. These requests expose non-public devices and servers to the internet, increasing the risk of a cross-site request forgery (CSRF) attack, and/or information leakage. To mitigate these risks, Chrome deprecates requests to non-public subresources when initiated from non-secure contexts, and will start blocking them in Chrome 92 (July 2021). See [Restrict "private network requests" for subresources from public websites to secure contexts.  - Chrome Platform Status](https://www.chromestatus.com/feature/5436853517811712)  for more details.

![image-20220222-140812](https://user-images.githubusercontent.com/50147765/156372231-19d125f9-c5fe-47df-8b6e-a3bc28c83f6c.png)

**Comment by natechadwick** [comment]
I don't think this one is really a bug, it seems like it is happening because you are running the instance on your local machine and chrome is seeing that as accessing a private network address.  if you see this when accessing a deployed server then we would need to look at it.
