### ISSUE TITLE
Adding a Template from a URL from an existing site does not work.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#436]
This was reproduced on Version 8.0.3 Build 111

Behavior:  When trying to add a template from a URL on an existing site, the dialog box just sits there at initializing and does nothing.

Steps to reproduce:
1) From the Design component, choose Add Template from the Action Menu.
2) When the dialog box appears, select the radio button that says "Enter page URL from an existing site".

![image-2022-02-23-13-53-28-325](https://user-images.githubusercontent.com/50147765/156373300-5e0b46af-b7ad-4800-b28e-a06cb34120ef.png)

3)  Add the following URLhttp://samples.percussion.com/

![image-2022-02-23-13-54-11-770](https://user-images.githubusercontent.com/50147765/156373610-8dbdee5d-4985-43c9-85f7-8d2cec480dab.png)
4) Hit Save.  The following dialog box appears and just sits there forever.
![image-2022-02-23-13-55-08-484](https://user-images.githubusercontent.com/50147765/156373929-516387dc-4ad5-4fee-b61f-04c12721750f.png)

As the dialog box now only has the option for close or done, I cannot bounce over to the Process Gadget to see if it is running.  I do not see any errors on the Java console.  I opened another browser session, added the process gadget, did the steps again and it shows nothing:
![image-2022-02-23-13-57-13-482](https://user-images.githubusercontent.com/50147765/156373801-64072d71-9b53-4952-af03-09da4a8b0903.png)

**Comment by natechadwick** [comment]
@ramdev1980 Can you look at this.  Try to import https://www.intsof.com as a site.  Step through the code and figure out why the import is exiting after 1 page.
