### ISSUE TITLE
Unable to select a target location for a new Asset

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#441]
This was reproduced on Version 8.0.3 Build 114

Behavior:  You cannot select a target destination when creating a new asset from the Home screen.
![image-2022-02-28-08-15-52-695](https://user-images.githubusercontent.com/50147765/156383632-c46e757b-e45a-4e18-a3ac-06f364b627f1.png)

I tried clicking on the select box, folder icon and file name.  Nothing gets selected.

Steps to reproduce:  
1)  From the Home screen - click the Add New button.
2)  Choose the radio button Asset and click Next
3) On the Choose Target location side - put the radio button to All folders.
![image-2022-02-28-08-17-19-901](https://user-images.githubusercontent.com/50147765/156383757-fb039f63-b932-41b7-8473-8301edfe088e.png)

4) Expand down as far as you can, but you cannot choose the location from the select boxes.

Additional behavior - after I created 1 asset during the testing session, it behaved differently.  It reads assets created thru the Add New on Home, but not assets and targets under the dashboard.

**Comment by natechadwick** [comment]
Closing as this looks resolved on current version.
