### ISSUE TITLE
If Click Advanced search is selected, you cannot go back to plain search Text box.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#442]
This was reproduced in Version 8.0.3 Build 114

Behavior - From the Home Screen, I chose "Search".  The following dialog box appears:
![image-2022-02-28-08-39-11-213](https://user-images.githubusercontent.com/50147765/156384475-c52ed833-71ec-490a-b83c-c9b25811155e.png)

If I click Advance Search, additional fields open up
![image-2022-02-28-08-39-47-447](https://user-images.githubusercontent.com/50147765/156384560-7db260e2-61e2-4c04-8c09-7b25f9843873.png)

If I hit cancel - the dialog box closes.

If I hit Search again, the same dialog box opens:
![image-2022-02-28-08-41-06-017](https://user-images.githubusercontent.com/50147765/156384681-ef16bff2-f5f2-4ba4-badd-dc60023ce6e7.png)

but it should go to the original simple text search first.

The only way to get back the original  simple keyword search screen is to log out of CMS and log back in.

**Versions Affected**
* 8.0.3
* 8.1.1
* 8.1.2
* 8.1.3

**Comment by natechadwick** [comment]
This is still an issue on 8.1.3
