### ISSUE TITLE
The sorting icon for Publishing History on the Operation icon is obscured by the column name.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#445]
This was reproduced on Version 8.0.3 Build 114

When I was testing the Publishing History sorting, I noticed that the sorting character "v" is obscured by the column title "Operation".
![image-2022-02-28-15-52-00-381](https://user-images.githubusercontent.com/50147765/156397347-7717c7d7-f16e-4623-9cc6-bb4349740f33.png)

You need to toggle your mouse a bit for the up/down character to appear.

**Comment by natechadwick** [comment]
The column sort seems to work ok. Looks like it was fixed.
