### ISSUE TITLE
Removing a Gadget from the dashboard should have a clearer confirmation message.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#446]
This issue was reproduced in Version 8.0.3 Build 114

I attempted to remove the Activity Gadget from the dashboard and I got a confirmation message:
![image-20220301-154858](https://user-images.githubusercontent.com/50147765/156397907-67314d8f-884f-42ee-a00b-90aa77d9c447.png)

The message should be changed from:  “Are you sure you want to delete the Activity gadget?” to 

“Are you sure you want to delete the Activity gadget **from the Dashboard**”?

And end user could easily believe that you are removing it entirely from the Gadget tray and system.

**Comment by natechadwick** [comment]
@NxPerc2019 I changed the language from "delete" to "remove" - does that soften the message enough?

**Comment by NxPerc2019** [comment]
That is definitely better, but I am not sure it is a matter of "softening" instead of clarity.  I know that I hesitated for a moment wondering if the Gadget would be removed from just the dashboard or the entire product.  If you have already made the change, that will work.
