### ISSUE TITLE
Rhythmyx Upgrade to 8.0.3 from Rhythmyx 7.3.2 will fail if non-installer created indexes exist on tables.

### ISSUE THREAD

**Issue by sonyDeswal** [percussion/percussioncms#454]
When User tries to upgrade Rhythmyx(7.3.2) to CMS(8.0.3) it fails with the error: Not able to Drop Indexes In table PSX_OBJECTRELATIONSHIP.

**To Reproduce**
1. Install 7.3.2 Out Of the box.
2. Start Server and make sure 7.3.2 is installed OK and is running.
3. Upgrade this instance to 8.0.3…

**Expected behavior**
Upgrade should be successful.

**Screenshots**
Indexes in the screenshot are not deleted
![image](https://user-images.githubusercontent.com/29978602/156779527-dd70ea53-df47-407b-8985-ed3874a9fe40.png)

**Comment by natechadwick** [comment]
The fix for this should be to drop and log any unexpected indexes that we encounter, in some cases the installer may need updated to generate new indexes if a needed index is missing on a frequently queried field.
