### ISSUE TITLE
Inappropriate Validation Error when adding a new Workflow with a number in the title

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#457]
This was reproduced in Version 8.0.3 Build 114
![Build114](https://user-images.githubusercontent.com/50147765/157052660-647886ba-48c8-4c7e-8158-30ac5a5f3d58.png)

Behavior - A validation error pop-up occurs when I attempt to add a new Workflow with a number in the title:
![image-20220307-142239](https://user-images.githubusercontent.com/50147765/157052714-b388eded-a9df-45b6-8440-0349bd6cc326.png)

Steps to reproduce:

 From the Admin Component, go to the Workflow Tab.  

Click on the “+” icon to create a new workflow.

For the Workflow name - I typed in 8883TestWF.
![image-20220307-142403](https://user-images.githubusercontent.com/50147765/157052813-bded7408-9fbc-45fc-8629-9a3523a4e68d.png)

Hit Save.  Validation Error occurs.
![image-20220307-142438](https://user-images.githubusercontent.com/50147765/157052925-4ac489a0-1a19-41bc-8a95-784ca87ba840.png)

**Comment by NxPerc2019** [comment]
Additional information:  Numbers, underscores and dashes will not work if they are the first character in the Workflow name.  If those characters are anywhere else but at the start of the Workflow name - they will work.

**Comment by natechadwick** [comment]
resolved with [0a48a2](https://github.com/percussion/percussioncms/commit/0a48a228056ab4e7d5a8a2d9c5ebf20ac99c92ef)
