### ISSUE TITLE
7.3.2 to 8.1.1- Upgrade fails with "login failed" error post deleting the problematic index.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#460]
Workaround: User needs to provide database credentials again in the rxrepository.properties file present under<install_directory>\rxconfig\Installer

BUILD FAILED

C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\install.xml:458: The following error occurred while executing this line:C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\install.xml:489: The following error occurred while executing this line:C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\install.xml:222: The following error occurred while executing this line:C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\installRepository.xml:235: Login failed for user 'sa'. ClientConnectionId:72762930-f12d-4292-9bbc-ccbdcde626cbat org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:582)at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)at org.apache.tools.ant.Task.perform(Task.java:350)at java.util.Vector.forEach(Vector.java:1277)at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)at org.apache.tools.ant.Task.perform(Task.java:350)at org.apache.tools.ant.Target.execute(Target.java:449)at org.apache.tools.ant.Target.performTasks(Target.java:470)at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)at org.apache.tools.ant.Project.executeTarget(Project.java:1374)at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)at org.apache.tools.ant.Project.executeTargets(Project.java:1264)at org.apache.tools.ant.Main.runBuild(Main.java:818)at org.apache.tools.ant.Main.startAnt(Main.java:223)at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)at com.percussion.ant.PSAntLauncher.main(PSAntLauncher.java:41)Caused by: C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\install.xml:489: The following error occurred while executing this line:C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\install.xml:222: The following error occurred while executing this line:C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\installRepository.xml:235: Login failed for user 'sa'. ClientConnectionId:72762930-f12d-4292-9bbc-ccbdcde626cbat org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:582)at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)at org.apache.tools.ant.Task.perform(Task.java:350)at org.apache.tools.ant.Target.execute(Target.java:449)at org.apache.tools.ant.Target.performTasks(Target.java:470)at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)at org.apache.tools.ant.Project.executeTargets(Project.java:1264)at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)... 33 moreCaused by: C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\install.xml:222: The following error occurred while executing this line:C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\installRepository.xml:235: Login failed for user 'sa'. ClientConnectionId:72762930-f12d-4292-9bbc-ccbdcde626cbat org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:582)at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)at org.apache.tools.ant.Task.perform(Task.java:350)at org.apache.tools.ant.Target.execute(Target.java:449)at org.apache.tools.ant.Target.performTasks(Target.java:470)at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)at org.apache.tools.ant.Project.executeTargets(Project.java:1264)at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)... 46 moreCaused by: C:\Users\KULDEE~1.MAL\AppData\Local\Temp\percInstallTmp_7935024202163639150\rxconfig\Installer\installRepository.xml:235: Login failed for user 'sa'. ClientConnectionId:72762930-f12d-4292-9bbc-ccbdcde626cbat com.percussion.ant.install.PSTableAction.execute(PSTableAction.java:245)at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)at org.apache.tools.ant.Task.perform(Task.java:350)at org.apache.tools.ant.Target.execute(Target.java:449)at org.apache.tools.ant.Target.performTasks(Target.java:470)at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)at org.apache.tools.ant.Project.executeTargets(Project.java:1264)at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)... 58 more

**Comment by natechadwick** [comment]
@sonyDeswal  Isn't this fixed by the encryption update?  We do need to add help / doc on requiring the unlimited encryption if users are using an older JRE that doesn't have it turned on by default.

**Comment by sonyDeswal** [comment]
Yes Nate, this is fixed. And correct, we need to add help/doc to check in case Encryption Fails, need to verify unlimited encryption is turned ON in JRE.
