### ISSUE TITLE
Edit Workflow field (s) get disappear in case validation message for allowed character is fired.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#468]
Login CMS application and navigate to Admin screen.

Click on pencil icon to edit the workflow.

Enter special characters like dot (.) for the field of Name and click on Save button.

Click on OK button of validation prompt.

Observe that fields for workflow editable form gets closed and error is logged on console.

**Comment by natechadwick** [comment]
Can't reproduce.  Looks like it was resolved.  Closing.
