### ISSUE TITLE
On add/edit workflow, validation message is different for different characters.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#469]
1. Navigate to Admin screen of CM.
2. Click on + button to add a new workflow.
3. Enter characters and add . (dot) for the field of Name and click on Save button.
4. Observe the validation message. “Invalid character in workflow name. Characters allowed are: a-z, 0-9, -, _ and [space].”
5. Close the validation message.
6. Now, enter / for the field of Name and click on Save button.
7. Observe the validation message. “Workflow names can only include letters, numbers, space, _ or - characters and must be 1 to 50 characters long.”

**Comment by natechadwick** [comment]
This looks to be resolved.  Closing.
