### ISSUE TITLE
Pop up for No Publishing History has issues on the dialog box.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#475]
This has been reproduced on Version 8.0.3 Build 114
![Build114](https://user-images.githubusercontent.com/50147765/157910806-6f29cec7-6617-44de-b615-bab850b4cf1f.png)

Behavior:
1) The title of the Popup is not showing page name:
2) There is no "Close" button on dialog box.  The only way off of the dialog box is to refresh the CMS.
![image-2022-03-11-11-40-48-861](https://user-images.githubusercontent.com/50147765/157910895-25a837cd-68ab-4edf-b62c-23e6a4d40e77.png)

Steps to reproduce:
1)  Identify a page that has not been published:
From the View menu - Choose Publishing History.  The dialog box will appear.

You will need to refresh the browser page for the CMS to get out of the dialog box.

**Comment by natechadwick** [comment]
@NxPerc2019  Is this still happing in 8.1.1?

**Comment by NxPerc2019** [comment]
On the following nightly build of 8.1.1 (see attached Word doc for build number) and I am still seeing the following:
1.  The OK button is now visible; however, the dialog box is so big that it makes the java console needs to be resized to be almost unusable in order to hit the button.  
2. The page names are still missing on the dialog box.

See the attached screenshot.
![image (1)](https://user-images.githubusercontent.com/50147765/181307433-4a6fc76d-ae7b-435b-8aa0-7e4177426e86.png)
[07272022Nightly8.1.1.docx](https://github.com/percussion/percussioncms/files/9201241/07272022Nightly8.1.1.docx)

**Comment by natechadwick** [comment]
@NxPerc2019  Thanks!  I will leave it as open. If you select a page that has publishing history does the dialog perform as expected?

**Comment by NxPerc2019** [comment]
@natechadwick - the answer to your question is Yes!  For pages that have been published, you can see the publishing history as expected.  
![image](https://user-images.githubusercontent.com/50147765/181312461-dfafab56-016d-44ff-bce8-04acffc24307.png)

**Comment by natechadwick** [comment]
Test on 8.1.3 - dialog has a close button if there is no publishing history so closing this out.
