### ISSUE TITLE
Custom Styles config for TinyMCE being overwritten on upgrade

### ISSUE THREAD

**Issue by acharliekelly** [percussion/percussioncms#476]
**Description**
TinyMCE custom styles configuration is overwritten by the upgrade.

**To Reproduce**
1. Create and save custom styles for TinyMCE
2. Upgrade CMS to 8.0.3
3. Open TinyMCE and look for custom styles

**Expected behavior**
Custom styles should still be available after upgrade

**Comment by Yashdeep2001** [comment]
@acharliekelly where is the custom styles file located that is being overwritten
