### ISSUE TITLE
Inline link processor running during full publish

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#478]
**Describe the bug**
Updated to the 8.0.3 version of the cms and tried to edit a rich text widget on a page.  The content in the widget contained inline links, and these links appeared to be broken (red error icon appeared next to each link), so they needed to be re-linked.  A dialog box also came up with an error that said "Transaction rolled back because it has been marked as rollback-only".

**To Reproduce**
1. Create a few pages anywhere in the cms.  Edit and approve each of those pages.
2. Go to the Assets folder, click any subfolder, and click New Asset at the top right corner of the cms
3. Click “Rich Text” asset
4. Click “insert link” to create a few links to each of the pages created in step 1
5. Submit and approve the rich text asset
6. Create a new page somewhere in the site.  Edit the page
7. In the Layout tab, add a rich text widget to it.  Switch to the Content tab
8. Drag the rich text asset that was approved in step 5 onto to rich text widget
9. Submit and approve this new page
10. Update to version 8.0.3
11. Start a full publish
12. Edit the page that contains the rich text widget with inline links and check if the links are broken 

**Expected behavior**
Inline links should not break after the update to 8.0.3

**Comment by natechadwick** [comment]
Closing as we haven't been able to reproduce the behavior.
