### ISSUE TITLE
732 patch install not removing older version of bouncy castle - 

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#486]
**Describe the bug**

Installing the latest rhythmyx patch pre-upgrade to 8.1.1 should be  removing the previously installed bouncy castle jars from the JRE(64)/lib/ext folder but the patch fails to remove them.  after patching,  starting via the jetty service causes annotation processing to take a very long time 300k+ ms and the service appears to hang.  

The 8.1 upgrade needs to remove the bouncy castle jars from ext if they are found and the 7.3.2 patch should be updated so it correctly removes them.

**Comment by sonyDeswal** [comment]
1) Remove BC jars from JRE/lib/ext as part of 8.1.1 upgrade in install.xml

**Comment by natechadwick** [comment]
Closing issue. If it tests ok, please remove the Ready for QA label. If there is still a problem, please re-open and remove the Ready For QA label - label - Re-Opened.

**Comment by mariosm1** [comment]
Tested upgrading a Rhythmyx instance on 732_20211210 patch level.  The existing bc* jars were removed from the JRE and JRE64 folders.
