### ISSUE TITLE
Rich Text Widget - Emoji's in the Rich Text Editor (TinyMCE) are not saving down.

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#533]
Behavior:  I added a few emoji’s to the content in a Rich Text Widget using the TinyMCE Rich Text editor, and they would not save down.  They disappear in the CMS Editor pane, they do not publish and when I go back into edit mode on the page, the emoji’s are gone.  There were no errors in either the jetty server or Java console.

Steps to reproduce:

1. Create a page using a Rich Text Widget.

2. On the Content pane, click the pencil to edit the Content.

3. Add some emoji’s into the editor section:
![emoji-1](https://user-images.githubusercontent.com/1232206/181257333-72f4f98a-1665-4f77-8ef1-2c04c03f6674.png)

4.  Click Save

5.  Look in the Editor pane and you will see the emoji’s are not there:
![emoji-2](https://user-images.githubusercontent.com/1232206/181257395-fca3f409-9a86-449a-b9be-c5a84e4e98d9.png)

6.  Submit - Approve and publish the page.

7.  Confirm that the emoji’s do not appear on the published page:
![emoji-3](https://user-images.githubusercontent.com/1232206/181257441-96fa37cd-499c-455d-8394-d48562c2762a.png)

8.  Go back to the Content pane and put the page in Edit mode.  You will see the emoji’s are also gone in the editor: 
![emoji-4](https://user-images.githubusercontent.com/1232206/181257479-6b55e57e-1472-42e6-8a16-62b46047a7e8.png)

Again, there are no errors in the Java Console or Jetty server.

### Environment

This was reproduced on the following nightly build of 8.1.1:

**Comment by natechadwick** [comment]
Closing issue. If it tests ok, please remove the Ready for QA label. If there is still a problem, please re-open and remove the Ready For QA label - label - Re-Opened.

**Comment by Yashdeep2001** [comment]
![image](https://user-images.githubusercontent.com/103224298/190478856-245f613f-fe7e-4a8d-ad35-c09c7c32e7fe.png)
Server error whenever I try to save with emojis

**Comment by NxPerc2019** [comment]
I retested this on the following Nightly build:

![image](https://user-images.githubusercontent.com/50147765/207332663-29ab00d4-af67-4f7b-baa7-17735b5c572f.png)

and the emojis all saved and rendered correctly on the published page:
![image](https://user-images.githubusercontent.com/50147765/207333224-9c2fbcec-92a8-47c0-9554-0a958cf3eb1e.png)

I removed the "Ready for QA" tag.
