### ISSUE TITLE
Update copyright year for devtools.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#542]
![image](https://user-images.githubusercontent.com/77011198/156368558-5615c00e-6408-4267-9915-f39e76b1ffc8.png)
![image](https://user-images.githubusercontent.com/77011198/156368713-b4562469-0d6a-421d-a7e7-99ea2a01391d.png)

**Comment by rgarg24** [comment]
Nate, I have checked and copyright year is coming fine for both Package Builder and Rhythmyx Content Explorer. 
It is not coming correct for workbench. So, I have corrected that.
