### ISSUE TITLE
Workbench-NPE Errors when deleting objects (slots, templates, content types)

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#546]
1. Connect workbench application with CM server.
2. Right Click on any Content Type and select Delete.
![image](https://user-images.githubusercontent.com/77011198/158581118-4e9bd37a-fd4a-4731-a5d5-a665279feea5.png)

3. Click on Ok button of confirmation prompt.
![image](https://user-images.githubusercontent.com/77011198/158581221-1e58dddb-e91c-46da-8666-f6ac3677fdc2.png)

4. Observe the error appeared on the screen.
![image](https://user-images.githubusercontent.com/77011198/158581231-49b90cca-7d52-4c88-9a0f-39aeb4bb956e.png)

5. No error logged on jetty server.

**Comment by natechadwick** [comment]
closed by fix for percussion/percussioncms#547
