### ISSUE TITLE
Workbench- Appropriate error message not showing if the user try to login workbench application with invalid credentials; Connection to Server failed due to unknown reason.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#548]
1. Bring up the CM server.
2. Launch Workbench application.
3. Enter valid server name, port and invalid credentials.
![image](https://user-images.githubusercontent.com/77011198/158572426-081852fd-7623-4401-9339-5bd58233f968.png)

4. Click on Connect button and observe the error message.
![image](https://user-images.githubusercontent.com/77011198/158572499-c63b57c2-b66b-41d7-933a-8842716ebec4.png)

**Comment by natechadwick** [comment]
not really a bug
