### ISSUE TITLE
Server Admin- "com.percussion.conn.PSServerException: null" appears on executing the dump cache from Monitor tab of Server Admin.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#549]
1. Connect Server Administrator to CM server.
2. Click on Monitor tab.
3. Enter **dump cache** in the Command text box and click on Execute button.
4. Observe the error.
![image](https://user-images.githubusercontent.com/77011198/157664514-3851c8ff-6fae-4f2f-8773-d6e0ad1a1908.png)

**Comment by natechadwick** [comment]
Should be resolved by:  https://github.com/percussion/percussioncms/commit/cb1ad2e710298ed9d6e8810fc28292ea1c8c89d1
