### ISSUE TITLE
Rhythymx upgrade to 8.1 fails if using oracle database

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#559]
Set up a Rhythmyx instance with an oracle database

Run the perc-distribution-tree.jar and point it to the Rhythmyx installation

Build will fail with the error at the end of the attached install.log

Acceptance Criteria

Build successful is shown after running the installer

Instance starts up without errors after 8.1 upgrade

**Comment by mariosm1** [comment]
DB has been restored and I updated the IMG_ALT lengths to 800 characters.  The instance is also starting up, so it just needs to be upgraded.

**Comment by mariosm1** [comment]
The upgrade failed with a different error -
```
PSTableAction] 13:29:59.677 [main] ERROR com.percussion.install.PSLogger - com.percussion.tablefactory.PSJdbcTableFactoryException: Unable to process schema changes for table (PSX_WB_HIERARCHY_NODE_PROP): [1] 23000: ORA-02298: cannot validate (PERCUSSION.) - parent keys not found
[PSTableAction]   C:com.percussion.ant.install.PSTableAction:L:211
BUILD FAILED
/tmp/percInstallTmp_9139404764313789671/rxconfig/Installer/install.xml:595: The following error occurred while executing this line:
/tmp/percInstallTmp_9139404764313789671/rxconfig/Installer/install.xml:626: The following error occurred while executing this line:
/tmp/percInstallTmp_9139404764313789671/rxconfig/Installer/install.xml:205: The following error occurred while executing this line:
/tmp/percInstallTmp_9139404764313789671/rxconfig/Installer/installRepository.xml:224: com.percussion.tablefactory.PSJdbcTableFactoryException: Unable to process schema changes for table (PSX_WB_HIERARCHY_NODE_PROP): [1] 23000: ORA-02298: cannot validate (PERCUSSION.) - parent keys not found
```

**Comment by mariosm1** [comment]
The upgrade with today's build was successful - just need to remove backup tables for RXS_CT_SHAREDIMAGE.

**Comment by natechadwick** [comment]
Closing issue. If it tests ok, please remove the Ready for QA label. If there is still a problem, please re-open and remove the Ready For QA label - label - Re-Opened.

**Comment by mariosm1** [comment]
Tested upgrading a 7.3.2 Rhythmyx instance w/ oracle to 8.1 and it was successful.
