### ISSUE TITLE
Cms Page, Template, and Widget content type objects are visible in ContentExplorer search, should be hidden

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#568]
Install 8.1.1

Create a site and few pages with contents and widgets on it.

pages and widgets/ assets created on cms , should not be visible in Content Explorer Search, as in image below index.htm (page)  should not be visible.

![cx-objects](https://user-images.githubusercontent.com/1232206/181292800-049cb4ad-2c10-4d5c-95ec-8af203d0ae54.png)

**Comment by Yashdeep2001** [comment]
It is no longer visible
![image](https://user-images.githubusercontent.com/103224298/187222390-b68a1573-1ac7-4bc8-9561-00f86fbf681f.png)

**Comment by natechadwick** [comment]
Closing issue.  If it tests ok, please remove the Ready for QA label.  If there is still a problem, please re-open and remove the Ready For QA label - label - Re-Opened.

**Comment by Yashdeep2001** [comment]
![image](https://user-images.githubusercontent.com/103224298/190217366-14361bad-9ce2-43d9-a165-b7dd906ae7a2.png)
Retested this is fully functional.
