### ISSUE TITLE
Design Component - Preview of pages using templates in thumbnails are not showing template design.

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#569]
Behavior:  When testing the Design Component, I looked at templates and the pages that they are associated to each template.  There is a magnifying glass (thumbnail) next to each page which allow the user to preview the associated pages for each template.  When you look at that preview, there are no design elements or content in these previews.

The test instructions are:  

The user should see the thumbnail for page on hovering on the preview icon for the page.
The thumbnail should have title on top and page path on bottom.

This is what it looks like:

![thumb-1](https://user-images.githubusercontent.com/1232206/181293389-8f9181ce-5a5a-44a5-8fcf-6ba9b8900ad9.png)

The template has content in it that looks like this:
![thumb-2](https://user-images.githubusercontent.com/1232206/181293409-33040119-11b6-4455-b064-7c0fd2ed9bc4.png)

![thumb-3](https://user-images.githubusercontent.com/1232206/181293435-8bc89411-3527-4f22-a2b2-4d8a89cfa998.png)

**Comment by NxPerc2019** [comment]
I retested this with the following build: 
![image](https://user-images.githubusercontent.com/50147765/185946073-0d136f00-8317-449a-9fd0-f1d7d8224a0b.png)

I can now see the images and the correct settings on pages that are on the template when I click on the magnifying glass on the page.

![image](https://user-images.githubusercontent.com/50147765/185946401-6a1927c3-e9ea-474a-a7c5-c47914abb862.png)

![image](https://user-images.githubusercontent.com/50147765/185946519-763b7b16-1c7e-4147-ba75-79b8069ecdf7.png)

I will close this for now.

**Comment by NxPerc2019** [comment]
I retested this on 12/3/2022 with the following nightly build:  
![image](https://user-images.githubusercontent.com/50147765/207337197-ab3474b8-ec9e-4740-84e3-13032d0c9503.png)

and can confirm that every page listed under the templates has the correct preview when looked at thru the magnifying glass.

![image](https://user-images.githubusercontent.com/50147765/207339101-122f682e-d021-4d2c-9f49-d6062a48b353.png)


![image](https://user-images.githubusercontent.com/50147765/207338383-b3f417d4-f4b2-4907-a345-fa0b020b7154.png)

I will removed the "Ready for QA" flag at this time.
