### ISSUE TITLE
Need better messaging when attempting to delete the default publishing server.  

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#577]
Currently, when you attempt to delete the default publishing server for a site, errors occur that indicate "Server Error"  

![image](https://user-images.githubusercontent.com/50147765/181782959-b370825a-4ec9-48ea-b87c-2fd7084b1ecd.png)

Errors also get reported in the server log.  See attached:

[07292022 delete pub server.txt](https://github.com/percussion/percussioncms/files/9220832/07292022.delete.pub.server.txt)

This is reproduced on the following nightly build of 8.1.1
![image](https://user-images.githubusercontent.com/50147765/181783208-cb3eb3a3-188a-4309-a1a5-3fa9a2008826.png)

There are 2 possible ways to resolve this:
1) The user will see a message like "Deleting the default publishing server is not allowed"...or something to that effect    OR
2) Disable the trash can icon on the default publishing server configuration page.  

**Versions Affected**
* 8.0.3
* 8.1.1
* 8.1.2
* 8.1.3

**Comment by ramdev1980** [comment]
If we have to disable the delete button and test then the estimate is 1 day 
if we have to change the error message then 2 days.

**Comment by ramdev1980** [comment]
If we have to disable the delete button and test then the estimate is 1 day 
if we have to change the error message then 2 days.
