### ISSUE TITLE
Incremental Publishing - Publish related items being deselected is being ignored and related items are getting published regardless.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#589]
Steps to reproduce:

1. I made sure that the "Publish related items" was deselected on may staging server.  (see screenshot below).

![image](https://user-images.githubusercontent.com/50147765/182886917-f0109c2f-f12d-41cc-bc0a-bea41203bded.png)

2.  I created 2 pages (ABC.html) and (DEF.html) with a rich text widget on both pages.  On ABC.html I added an image in the Rich Text Widget  that I had previously uploaded Polls Vote error.png

![image](https://user-images.githubusercontent.com/50147765/182888446-cc60cd7f-5a61-4eb4-85c4-1bf1c4b06029.png)

4.  On DEF.html, I added a link to TESTAsset3.pdf in the Rich Text Widget.

![image](https://user-images.githubusercontent.com/50147765/182888698-656a3ae2-e356-480d-855a-16d463a01469.png)

5.  I put both ABC and DEF html files into Pending status.

![image](https://user-images.githubusercontent.com/50147765/182888950-7a424a72-cce8-4b83-a811-774fa1fb24d2.png)
![image](https://user-images.githubusercontent.com/50147765/182889025-8343f761-4bd9-4a5c-837b-e1da07944347.png)

7.  I went to the publishing queue and there were no items in the Related Item publishing queue.
![image](https://user-images.githubusercontent.com/50147765/182889195-4ec9c49c-7251-4006-83af-7b4099fe92f2.png)
Polls Vote error is in the queue

Polls Vote image automatically got put into Pending state
![image](https://user-images.githubusercontent.com/50147765/182889522-dd1090f3-fe63-4d92-9de5-d8844be317e2.png)

For the TestAsset3.pdf  is also in pending state as well, but it is not in the publishing queue:
![image](https://user-images.githubusercontent.com/50147765/182889765-4ca5e1ed-fb2e-4475-a271-e0a7dc57d0ea.png)

![image](https://user-images.githubusercontent.com/50147765/182890045-fbcd0909-0e1f-49c2-b087-fcee45d05cfd.png)

After publishing completes, the PDF doclink opens when launched and it should NOT be.

![image](https://user-images.githubusercontent.com/50147765/182890360-22eb618e-87c3-47c0-98c5-10ff24e10d42.png)

![image](https://user-images.githubusercontent.com/50147765/182890616-5109dc36-d21f-450d-acf2-f474e923b05d.png)

When I click on the link, it launches.
![image](https://user-images.githubusercontent.com/50147765/182890709-c11892c4-3978-42af-9a3b-c9fcf78a980e.png)

**Comment by natechadwick** [comment]
Closing as I think there is a misunderstanding on what publish related items does vs what the normal incremental does.   If a related item is draft and publish related items is turned, then the publish will find any related un-approved pages or assets and prompt with a second dialog if you want to auto-approve and include them in the incremental publish.  Assets that are pending and related via managed links will always get picked up by an incremental publish.
