### ISSUE TITLE
Incremental Publishing - The logs do not automatically refresh after an incremental publish.  You need to refresh the browser in order to see publishing completed or not.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#590]
Steps to reproduce:

1.  Run a full publish - You will see the status of the publishing run and when it completes you see the results:

![image](https://user-images.githubusercontent.com/50147765/182891085-f0860a2a-5223-494d-8f00-92729eaf281d.png)
![image](https://user-images.githubusercontent.com/50147765/182891159-4b856820-aed4-4687-a731-0eda5fd5b624.png)

2.  Edit or create a new page and approve it.

![image](https://user-images.githubusercontent.com/50147765/182891542-ab4cb378-08ce-4c8b-9127-fcb66dc41e92.png)

3.  Go to the Publishing queue and look at the file to be incrementally published.  Hit Continue
![image](https://user-images.githubusercontent.com/50147765/182891716-cb0231b7-2cf3-4fb0-9c9e-be3b493827f8.png)
4.  The results will not appear until I refresh the browser

Before refresh
![image](https://user-images.githubusercontent.com/50147765/182893200-e86922eb-f5b1-44d2-b16a-1e5db7db0f48.png)

After refreshing the browser- the log shows:

![image](https://user-images.githubusercontent.com/50147765/182893664-d076ecad-0a68-4933-a0d6-ec1da07c85e9.png)

**Comment by natechadwick** [comment]
Needs tested to see if it can be reproduced.

**Comment by rgarg24** [comment]
Hi Nate, I tested it but it is working fine. So, closing this bug.
