### ISSUE TITLE
Exception in thread "FTSIndexQueue" after Jetty Startup

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#593]
I upgraded to the following nightly build of 8.1.1 (see screenshot)

![image](https://user-images.githubusercontent.com/50147765/183466974-c181e3be-01f5-46fc-a6d9-68149725ffb1.png)

After the server started, the console showed the information attached.  This was NOT written to the server log.

[08082022log.txt](https://github.com/percussion/percussioncms/files/9283466/08082022log.txt)

Per Development review:  

That related to the POI security update https://github.com/percussion/percussioncms/security/dependabot/39.  The security issue has been resolved.  This is a regression in the indexing of office documents only.

**Comment by NxPerc2019** [comment]
Additional info - Once the error occurs, you cannot cleanly shut down Jetty.  It hangs at "Shutting down Index queue" shutdown.  I had to close the console via the 'X" on the dos window and do an OS restart.  

![image](https://user-images.githubusercontent.com/50147765/183737663-18047cca-dc59-48bb-aa8f-5d1b3f5c75c8.png)

**Comment by natechadwick** [comment]
The different File types need uploaded as assets before search indexing in order to reproduce this.  You need a Word document, Excel, Powerpoint, and PDF assets to get the text extraction errors.
