### ISSUE TITLE
Image Slider Widget:  Implement a toggle for target =_blank property in external links

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#602]
Currently all external links are set to create a new tab with the property target=_blank.  This feature request would add a new toggle to the layout properties so that this property can be removed by users.

**Comment by natechadwick** [comment]
This could be done by modifying system/Packages/perc.widget.imageSlider/sys__UserDependency--rxconfig/Widgets/percImageSlider.xml and adding a layout property (maybe an enum) for the link target.  

The link target (search on target=) is in 3 places that would need to be updated to read the new layout property.  The default value for the new property would need to be _blank so as not to cause upgrade issues.

**Comment by natechadwick** [comment]
@mario-percussion I think all that is left on this is updating the version info for the widget so it updates correctly on upgrade.

**Comment by mariosm1** [comment]
Tested all target=_ options for internal and external links, also tested the "Images are links" checkbox in the image slider layout properties.  All of these are working.
