### ISSUE TITLE
Allow Certbot to create and access /.well-known folder in cms root

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#665]
**Describe the bug**
Certbot needs to verify that a domain points to the server you are running certbot from.  It needs to be able to reach the http://[cms-url]/.well-known  (full path is /.well-known/acme-challenge/{validationfile}  ), but this redirects to the login page for the cms.  We need to create an exclusion rule in the jetty config.

**Comment by natechadwick** [comment]
@matomario8 What was the final path that you settled on in the testing?

**Comment by natechadwick** [comment]
@rgarg24  This one is pretty easy.  In the system/ear/config/security/system-security-conf.xml need to add an anonymous entry for the ".well-known" folder.

**Comment by natechadwick** [comment]
Linking to CertBot docs: https://eff-certbot.readthedocs.io/en/stable/using.html
