### ISSUE TITLE
Lock the prefix for a widget once that widget has been created

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#680]
**Describe the bug**
If the prefix for a widget is changed on an existing custom widget, a duplicate widget will be created with the same name but a different prefix.  

**To Reproduce**
1. Create any custom widget with any fields, and deploy it.  Make a note of the prefix field in the general widget settings
2. Edit the widget again
3. Update the prefix, save, and deploy the widget again
4. Note that a second widget was created with that name.  The original widget is still there as well

**Expected behavior**
Expected behavior is that the widget prefix can not be changed (input box can be greyed out)

**Comment by matomario8** [comment]
Expected behavior should be that the widget prefix can not be changed

**Comment by ramdev1980** [comment]
Closing this as it has already been closed in previous release.
