### ISSUE TITLE
Comparison Tool fails to show diff of 2 revision versions with error: Failed to run compare tool

### ISSUE THREAD

**Issue by sonyDeswal** [percussion/percussioncms#682]
**Describe the bug**
ComparisonTool fails to show diff of 2 revision versions with error: Failed to run compare tool

**To Reproduce**
1. Go to Content Explorer.
2. Click on any generic content and right click to see menu.
3. Select "View" -> "EI Compare"
4. You will see a page launched with comparison  tool but whne click on [Compared], you see error:-  Failed to run compare tool

**Expected behavior**
Comparison should be displayed between 2 revision chanages.

**Screenshots**
![image](https://user-images.githubusercontent.com/29978602/201775724-c365f3dc-dcd7-4364-b0d3-6ad3b91ad5b5.png)

![image](https://user-images.githubusercontent.com/29978602/201775666-f34e8e04-2194-45c0-9b13-f46cf52aa8ef.png)

** If an error is occurring on the server (500 etc) attach the server.log if possible:**
You will see following error in server.log:-
![image](https://user-images.githubusercontent.com/29978602/201775958-60d792cb-9d22-47b2-a11f-4d8771124329.png)

**Additional context**
Need to remove dll dependency and should use a platform independent coparison tool.

**Comment by natechadwick** [comment]
Re-opening as not fully complete yet.
