### ISSUE TITLE
Private key dropdown greyed out on publishing config

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#690]
**Describe the bug**
You can not select a private key in the publishing server configuration even if there is a key located under Percussion/rxconfig/ssh-keys/

![im1](https://user-images.githubusercontent.com/32443983/204907010-af95c860-5156-4ad6-bb13-752a377f2c75.PNG)

**Comment by sonyDeswal** [comment]
This is working as expected in 8.1.1
