### ISSUE TITLE
CLOB data type on PERC_PAGE_METADATA_PROPERTIES causing tempdb to build up quickly

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#692]
**Describe the bug**
A query to the PERC_PAGE_METADATA_PROPERTIES table in the DTS seems to return a lot of extra data which may be due to the CLOB data type used in the textvalue column.   Attached is a csv of the queries to PERC_PAGE_METADATA_PROPERTIES:
[sqlserverDBTemp.csv](https://github.com/percussion/percussioncms/files/10135673/sqlserverDBTemp.csv)

**Comment by natechadwick** [comment]
Customer had tempdb grow to +50GB while the app was running this query from multiple connections.  It looks like in the PSMetadataQuery service is eagerly fetching, which might be causing the issue.  Will try to flip that to Lazy load the LOB fields to see if it resolves the problem.

**Comment by mariosm1** [comment]
Installed 8.1 version of the DTS with SQL server and added <prop key="hibernate.enable_lazy_load_no_trans">true</prop> to perc-datasources.xml.  It starts up alright and publishing to that DTS works with no errors.
