### ISSUE TITLE
Siteimprove plugin - add option to only scan pages and not assets

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#696]
**Is your feature request related to a problem? Please describe.**
The siteimprove plugin currently scans all assets and pages.  For systems with a lot of assets, this adds too many items to the queue and siteimprove takes a while to finish scanning.

**Describe the solution you'd like**
This feature would add an option to exclude assets from the siteimprove scan

**Comment by ramdev1980** [comment]
@natechadwick  We need your insight to understand this enhancement.

**Comment by ramdev1980** [comment]
com/percussion/integrations/siteimprove/task/impl/PSSiteimproveEditionTask.java
system/Packages/perc.gadget.siteImprove/sys__UserDependency--cm/gadgets/repository/perc_site_improve_gadget/perc_site_improve_gadget.xml

Need to go through these files for understanding the functionality.
