### ISSUE TITLE
Add Validation against known mime types when creating a page

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#736]
**Is your feature request related to a problem? Please describe.**
Invalid file names can be published, but can not be served by the webserver (for example "filename.-24").  This leads to some confusion about whether or not a page was published.

**Describe the solution you'd like**
With this improvement, we would like to prevent invalid file extensions in page file names.  For example, the page "filename-.24" should not get created with this validation, as .24 is not a known mime type.  Known mime types will be listed in the mimemap.properties

**Comment by natechadwick** [comment]
@rgarg24 Didn't you work on a fix for this one?

**Comment by natechadwick** [comment]
Fixed by https://github.com/percussion/percussioncms/pull/1206
