### ISSUE TITLE
Rhythmyx properties appearing on published images inside rich text widgets

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#757]
**To Reproduce**
1. Create an image asset
2. Add a rich text widget to a page and insert an image to it
3. Select the image asset you created
4. Publish the image and the page
5. Check the published page to see if the internal Rx attributes appear inside the <img> tag

**Expected behavior**
Any properties that can not be processed as HTML should not be published.  Examples:
rxinlineslot
sys_dependentid
sys_dependentvariantid
sys_relationshipid

**Comment by natechadwick** [comment]
This should be resolved by e9f389f0
