### ISSUE TITLE
"Unable to perform requested lazy initialization" error in DTS metadata.log

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#818]
**Describe the bug**
In version 8.1.2 on the DTS side, the error below appears in the metadata.log which seems to prevent the DTS from getting a working database session.  The database that was used in this example was mysql:

![im1](https://github.com/percussion/percussioncms/assets/32443983/d63202d3-6c19-473e-a625-65c4175a0ea1)

## Work Arounds
Adding the property below to the hibernate props in the _perc-datasources.xml_ file resolves the issue:
`<property name="hibernate.enable_lazy_load_no_trans" value="true"/>`
NOTE: This will decrease performance and shouldn't really be used long term.

**Comment by natechadwick** [comment]
@rgarg24 I think that you fixed this when working on another issue.  Can you confirm?

Thanks!
-n
