### ISSUE TITLE
Restoring a revision in quick edit state updates the "Last Modified" time on the original revision

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#891]
**Describe the bug**
Restoring to a revision that was left in quick edit state successfully creates a new revision with the restored content, but updates the "Last Modified" time on the original revision.  

<img width="689" alt="45345345" src="https://github.com/percussion/percussioncms/assets/32443983/1ddfacbd-10df-4b9c-8d94-375913afb0f5">

This does not affect items in Live or Pending state

**To Reproduce**
1. Edit an item that has several revisions in the revision history
2. Using the View->Revisions menu, try to restore to an older revision (in quick edit)
3. The "Last Modified" time on the older revision has now been updated to match the latest revision

**Expected behavior**
The Last Modified times on older revisions should not be updated.

```mermaid
flowchart TD
      A[Checkout Rev 5]  ---> B[Promote Revision 2 to 6] ---> C[Checkout Revision 6] ---> D[Revision 2 Should be Unchanged]

**Comment by natechadwick** [comment]
@rgarg24 Related doc:  https://percussioncmshelp.intsof.com/percussion-cm1/manage-content/pages/page-revisions/

**Comment by sonydeswal74** [comment]
Not Reproducing, It is working  as expected.

**Comment by sonydeswal74** [comment]
It is not working as expected when selected version for restore is in QuickEdit mode.
