### ISSUE TITLE
Duplicate RXSLOTTYPE entries added after 8.1.2 upgrade

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#892]
**Describe the bug**
Even if there are already navigation slots registered in the RXSLOTTYPE table, the 8.1.2 upgrade will create four duplicate navigation slots with the following id's:
510
511
513
516

**Expected Behavior**
If the slots already exist, the upgrade should skip creating them

**Comment by natechadwick** [comment]
Unable to reproduce on current version.
