### ISSUE TITLE
Green drag + drop indicator on widget slots doesn't always display

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#904]
**Describe the bug**
When dragging a widget over to a new widget slot, the green indicator doesn't display when hovering over multiple widgets in a row.  Example below:

![vid](https://github.com/percussion/percussioncms/assets/32443983/4e8bf332-ad72-4c04-b4d3-7e30b2c176df)

**To Reproduce**
1. Create a page or template layout with a few stacked widget slots so that there is no white space between them
2. Add some content to one of the widgets in the Content tab
3. Drag the content to a new slot, making sure to hover over two widgets in a row while dragging it

**Expected behavior**
The green indicator should always appear when dragging a valid widget to a slot.  You should not need to hover the mouse over white space first in order to see the indicator.

**Comment by ramdev1980** [comment]
Blocked by bug #980.

**Comment by natechadwick** [comment]
It's unclear to me what the type of asset is that is being dragged in the screenshot, I assume it is Rich Text.   Need to reproduce with a similar template layout. May be something off with the drag target size or something.

**Comment by natechadwick** [comment]
Note that drag and drop has similar issues in the Navigation editor.
