### ISSUE TITLE
New rich text widgets copy text from first rich text widget on the page

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#905]
**Describe the bug**
(see steps to reproduce)

**To Reproduce**
1. Open a page that contains a few rich text widgets that have text in them.
2. Add a new rich text slot from the Layout tab
3. Edit the slot in the Content tab
4. The widget will copy the text from another widget on the page

![image](https://github.com/percussion/percussioncms/assets/32443983/986dced4-01e8-41d8-a710-76f086fea127)

After double clicking the widget slot
![image](https://github.com/percussion/percussioncms/assets/32443983/72f57a0d-bed6-48c1-b34e-2fd4bf63d21e)

**Expected behavior**
The widget should be empty when you open it to edit.

**Comment by natechadwick** [comment]
@rgarg24  to look at after the fontawesome thing
