### ISSUE TITLE
VISIT_ID has no default value in the dts BLOG_POST_VISIT table 

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#923]
**Describe the bug**
"VISIT_ID has no default value"  -> This error will get logged in the DTS metadata log when a user clicks links in archive list widgets.  The environment this was tested on was upgraded to 8.1.2

**Expected behavior**
Manually setting the column to autoincrement with a query will fix the problem, but the column should be modified by the upgrade if autoincrement is not set.

**Comment by natechadwick** [comment]
@matomario8 Is this only on MySQL 8?

**Comment by mariosm1** [comment]
I still have to test it out on a local instance, will get back to you.

**Comment by mariosm1** [comment]
@natechadwick I think it is only MySQL 8.  It doesn't affect MySQL 5.7, the VISIT_ID was still set to auto increment after upgrading.

**Comment by natechadwick** [comment]
Seems related to this:  https://stackoverflow.com/questions/804514/hibernate-field-id-doesnt-have-a-default-value
