### ISSUE TITLE
Table HTML attributes removed after saving rich text widget

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#938]
Attributes like border and cellpadding are removed from table elements in rich text widgets (after saving the widget)

**To Reproduce**
1. Open a rich text widget and then open the source view to create a table.  You can also create a table using the Table dropdown
2. Make sure the table element has the following attributes `<table class="tableoutline" cellspacing="0" cellpadding="4" border="1">`
3. Save the Rich Text widget
4. Open the widget again and the border and cellpadding properties will be removed

**Expected behavior**
All table attributes should be kept on saving the widget if they are valid

**Comment by mariosm1** [comment]
Attributes can be added as styling by adding this property to the rx_resources/tinymce/config/customer_config_override.json

`"table_style_by_css": true`

**Comment by ramdev1980** [comment]
This needs to be changed here:
modules/perc-tinymce/src/main/resources/META-INF/resources/sys_resources/tinymce/config/default_config.json

see this :
https://www.tiny.cloud/docs/plugins/opensource/table/

Can be tested in installation dir:
C:\Percussion\Project_Installation\CMS\sys_resources\tinymce\config
