### ISSUE TITLE
Widget Display code does not save

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#942]
**Describe the bug**
Clicking Save on a widget does not save the display code.  All other information, like version or general info does save.

**To Reproduce**
1. Create a new widget
2. Add Content, fill out the required fields, and add some display code
3. Save the widget
4. Open the widget again for editing
5. Display code will be blank
6. (this occurs with existing widgets as well)

**Versions Affected**
* 8.1.2

**Comment by rgarg24** [comment]
The Display code was not saving as the html widget was not getting picked up while saving. This issue has now been fixed.
