### ISSUE TITLE
div.rxbodyfield elements are wrapped in new document

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#943]
**Describe the bug**
Anywhere rxbodyfield is used, such as a rich text or custom widget, the element is wrapped in `<html>` and `<body>` tags:
e.g.

```
<body>
...
 <html><head></head><body>  <div class="rxbodyfield">...some content</div> </body></html>
...
</body>
```

**To Reproduce**
1. Create a rich text widget
2. Add some content to it
3. Preview the page
4. View Page source and search for `<html>` tags to find the widget on the page

**Expected behavior**
The `<div class="rxbodyfield">` should not be wrapped in html or body tags

**Comment by natechadwick** [comment]
Confirmed - definitely a bug.
