### ISSUE TITLE
Hidden buttons in RichText Editor source code dialog 

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#950]
**Describe the bug**
When editing a Rich Text asset under the /Assets/... view (not page view), editing through the source code view hides the Confirm and Cancel buttons.  

**To Reproduce**
1. Edit a rich text asset
2. Click Tools > Source Code
3. Look for the confirmation button for the source view (not Save - this is for saving the rich text widget as a whole)

**Expected behavior**
Confirm and Cancel buttons should always be visible

**Comment by natechadwick** [comment]
Re-opening as this fix broke the source code view.  The height must be a number or the theme code fails to apply.  I think another pass at this using css might be better.
