### ISSUE TITLE
Fix GitHub Actions to only run on specific branches / main repository

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#965]
GitHub Actions seem to be running on random branches.  We need to prune not needed branches and update the GitHub Actions scripts in all existing branches so that they only run in the main repo and only on the targeted development / release branch.  Also need to better understand what happens with GitHub actions when the repo is forked.

**Comment by natechadwick** [comment]
@rgarg24 Would you mind looking at this one?

**Comment by rgarg24** [comment]
@natechadwick I have stopped yml files in workflows folder in .github folder for all the branches.

**Comment by natechadwick** [comment]
@rgarg24 I cleaned up the tags to remove all of those SNAPSHOT and nightly build tags.  There should only be tags for release versions left. Can you confirm the actions are disabled on those tags?

**Comment by natechadwick** [comment]
Not on local repo I had to run to clear tags deleted on origin from local and to remove tracking branches   deleted on orign on local.

``
git fetch --prune --prune-tags origin
git remote prune origin
``

**Comment by rgarg24** [comment]
@natechadwick Now there are 8 tags. All of these tags are in detached state. So, we cannot disable github actions on these tags.

**Comment by rgarg24** [comment]
We still need to check how forks works for github actions.
