### ISSUE TITLE
Unable to delete specific folders after update to 8.1.2

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#973]
**Describe the bug**
We converted a couple of Folders from Navigation sections to regular folders and then tried to delete the folders in the Finder.  The delete dialog comes up and closes and the UI refreshes but the Folder is still there and no entry is added to the recycling bin.

**Comment by natechadwick** [comment]
@rgarg24 Here is that issue on the Folder deletion.

**Comment by natechadwick** [comment]
@rgarg24 Was this fixed?

**Comment by rgarg24** [comment]
yes Nate it was fixed and the code was committed and pushed.
