### ISSUE TITLE
Unable to create a new asset using the New Asset toolbar button in the Finder

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#980]
**Describe the bug**
This behavior seems to be introduced in 8.1.3, worked fine in 8.1.2  In the Finder when you select an Asset folder and New Asset from the Toolbar the screen is refresh but the new Asset Dialog is never displayed preventing you from creating a new shared asset.

**Comment by natechadwick** [comment]
@ramdev1980  Did this behavior change after the rollback we did with PR #987 ?

**Comment by ramdev1980** [comment]
@natechadwick  yes, backing out the pull request, solve the problem. So I am closing this issue.
