### ISSUE TITLE
Blog post navigation issue

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#999]
**Describe the bug**
The blog posts have an issue: The “Newer Entries” and “Older Entries” links on any post doesn't work, they connect back to the blog page you’re on.

**To Reproduce**
1. Create blogs list
2. Create blog posts at least 3
3. In blog post set the "Location of blog navigation" as "Beneath blog post"
4. Try to navigate between blog post using “Newer Entries” and “Older Entries” links
5. It doesn't work.

**Expected behavior**
“Newer Entries” and “Older Entries” links should work.

**Comment by natechadwick** [comment]
@ramdev1980  You have to publish the blog posts and have a running DTS for this as well right?  Also didn't you have to edit the perc-security.properties files to stop the CORS error?
